### ISSUE TITLE
2.0.0 won't work with Greenhouses

### ISSUE THREAD

**Issue by mindw0rm** [BentoBoxWorld/Biomes#101]
### Expected behavior

The addons Biomes and Greenhouses work together, or at least side by side.

### Observed/Actual behavior

Startup errors which result in Biomes being disabled:
```[00:05:19 WARN]: [BentoBox] [Biomes] Level add-on not found. Some features from Biomes Addon will not work!
[00:05:19 WARN]: [BentoBox] Skipping Biomes as it is incompatible with the current version of BentoBox or of server software...
[00:05:19 WARN]: [BentoBox] NOTE: The addon is referring to no longer existing classes.
[00:05:19 WARN]: [BentoBox] NOTE: DO NOT report this as a bug from BentoBox.
[00:05:19 INFO]: [BentoBox] Gathering contribution data for: BentoBoxWorld/BentoBox, BentoBoxWorld/BSkyBlock, BentoBoxWorld/Biomes
[00:05:19 ERROR]: [BentoBox] Please report this stack trace to the addon's author(s): [BONNe] 
java.lang.NoClassDefFoundError: world/bentobox/greenhouses/Greenhouses
	at world.bentobox.biomes.BiomesAddon.lambda$allLoaded$5(BiomesAddon.java:178) ~[Biomes-2.0.0.jar:?]
	at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
	at world.bentobox.biomes.BiomesAddon.allLoaded(BiomesAddon.java:175) ~[Biomes-2.0.0.jar:?]
	at world.bentobox.bentobox.managers.AddonsManager.allLoaded(AddonsManager.java:680) ~[BentoBox-1.20.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at world.bentobox.bentobox.managers.AddonsManager.allLoaded(AddonsManager.java:669) ~[BentoBox-1.20.1.jar:?]
	at world.bentobox.bentobox.BentoBox.lambda$completeSetup$2(BentoBox.java:250) ~[BentoBox-1.20.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-333]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-333]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: world.bentobox.greenhouses.Greenhouses
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 15 more
```

This is really strange, because the class is only used if Greenhouses is present, which is it (see version output) and the class name/path seems correct to me (Greenhouses.class is at the given path in the jar, and using javap on the file also shows the expected class path). So it looks like some weird class loader error. 

We have a Minecraft 1.17.1  with Bentobox 1.19.0, Biomes 1.14.0 and Greenhouses 1.6.0 which does _not_ have this issue. 
The error occurred when I tried to upgrade that server to the newest versions, but it is reproducible with a new server with minimal setup. 

### Steps/models to reproduce

Create a new server, using the newest versions of Paper (git-Paper-333 (MC: 1.18.2)), Bentobox (1.20.1), BSkyBlock (1.15.2), Biomes (2.0.0) and Greenhouses (1.6.0) (all from https://download.bentobox.world/custom).
Start the server.

### BentoBox version

```
> bbox version
[00:06:52 INFO]: Running PAPER 1.18.2.
[00:06:52 INFO]: BentoBox version: 1.20.1
[00:06:52 INFO]: Database: JSON
[00:06:52 INFO]: Loaded Game Worlds:
[00:06:52 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[00:06:52 INFO]: Loaded Addons:
[00:06:52 INFO]: BSkyBlock 1.15.2 (ENABLED)
[00:06:52 INFO]: Greenhouses 1.6.0 (ENABLED)
```

### Plugin list

```
> plugins
[00:08:30 INFO]: Plugins (1): BentoBox
```

**Comment by BONNe** [comment]
Please yours dev version of greenhouses

**Comment by mindw0rm** [comment]
This works, thanks :)
