### ISSUE TITLE
Exception when markerinh0 attempted to tab complete is biomes info

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/Biomes#36]
####  Steps to reproduce the behavior:
1. Write /is biomes info and tab (?)

#### Expected behavior
Command works

#### Server Information:
[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []
 - OS: Ubuntu 18.04
 - Java Version: Java 11
 - BentoBox version: 1.5.2
 - Addons installed?
19.06 20:14:03 [Server] INFO Running PAPER 1.13.2.
19.06 20:14:03 [Server] INFO BentoBox version: 1.5.2
19.06 20:14:03 [Server] INFO Loaded Game Worlds:
19.06 20:14:03 [Server] INFO commands.bentobox.version.game-world
19.06 20:14:03 [Server] INFO Loaded Addons:
19.06 20:14:03 [Server] INFO AcidIsland 1.5.0
19.06 20:14:03 [Server] INFO Biomes 1.5.0.0
19.06 20:14:03 [Server] INFO Challenges 0.7.5
19.06 20:14:03 [Server] INFO Level 1.5.0
19.06 20:14:03 [Server] INFO Limits 0.2.1-SNAPSHOT
19.06 20:14:03 [Server] INFO WelcomeWarps 1.5.0
 - Other plugins?
Plugins (89): AdditionsAPI, AdminVedelem, AdvancedAchievements, antiRedstoneClock, AnvilRestrict, BentoBox, BestViewDistance, Brewery, BuntetesLogolo, ChangeSkin, ChatControl, ChatReaction*, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CustomOreGen, Duels, EnderContainers, EntityDetection, EpicHeads, Ercgenerator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, FastAsyncWorldEdit, HolographicDisplays, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv*, PickupSpawners, PlaceholderAPI*, PlayerHeads, PlugMan, PocketGames, PomaAdditions, ProtocolLib*, ShopGUIPlus, Shopkeepers, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, ViaVersion*, Votifier, VotingPlugin, WDLCompanion*, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

####  Additional context
```
[15:32:19] [Netty Epoll Server IO #3/ERROR]: Exception when markerinh0 attempted to tab complete is biomes info
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'is biomes info' in world.bentobox.acidisland.commands.AiCommand(is)
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:238) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabCompleteCommand(CraftServer.java:1783) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabComplete(CraftServer.java:1755) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.craftbukkit.v1_13_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[patched_1.13.2.jar:git-Paper-632]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[patched_1.13.2.jar:git-Paper-632]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:379) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:549) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:156) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:145) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-632]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.13.2.jar:git-Paper-632]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-632]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at world.bentobox.biomes.database.objects.BiomesObject.compareTo(BiomesObject.java:327) ~[?:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at world.bentobox.biomes.BiomesAddonManager.getBiomes(BiomesAddonManager.java:464) ~[?:?]
	at world.bentobox.biomes.commands.user.BiomesInfoCommand.tabComplete(BiomesInfoCommand.java:80) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.tabComplete(CompositeCommand.java:585) ~[?:?]
	at org.bukkit.command.Command.tabComplete(Command.java:95) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:232) ~[patched_1.13.2.jar:git-Paper-632]
	... 48 more
```

**Comment by BONNe** [comment]
Fixed in [Biomes-1.5.2.1-SNAPSHOT-b117](https://ci.codemc.org/job/BentoBoxWorld/job/Biomes/117/)
