### ISSUE TITLE
/is biomes null error

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/Biomes#37]
#### Description
/is biomes null error

####  Steps to reproduce the behavior:
1. use /is biomes

#### Server Information:
[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS: Ubuntu 18.04
 - Java Version: Java 11
 - BentoBox version: 1.5.2
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
20.06 13:08:42 [Server] INFO Running PAPER 1.13.2.
20.06 13:08:42 [Server] INFO BentoBox version: 1.5.2
20.06 13:08:42 [Server] INFO Loaded Game Worlds:
20.06 13:08:42 [Server] INFO AcidIsland_world (AcidIsland): Overworld, Nether, End
20.06 13:08:42 [Server] INFO Loaded Addons:
20.06 13:08:42 [Server] INFO AcidIsland 1.5.0
20.06 13:08:42 [Server] INFO Biomes 1.5.2.1-SNAPSHOT-LOCAL
20.06 13:08:42 [Server] INFO Challenges 0.7.5
20.06 13:08:42 [Server] INFO Level 1.5.0
20.06 13:08:42 [Server] INFO Limits 0.2.1-SNAPSHOT
20.06 13:08:42 [Server] INFO WelcomeWarps 1.5.0
 - Other plugins? [Do '/plugins' and copy/paste from the console]
Plugins (89): AdditionsAPI, AdminVedelem, AdvancedAchievements, antiRedstoneClock, AnvilRestrict, BentoBox, BestViewDistance, Brewery, BuntetesLogolo, ChangeSkin, ChatControl, ChatReaction*, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CustomOreGen, Duels, EnderContainers, EntityDetection, EpicHeads, Ercgenerator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, FastAsyncWorldEdit, HolographicDisplays, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv*, PickupSpawners, PlaceholderAPI*, PlayerHeads, PlugMan, PocketGames, PomaAdditions, ProtocolLib*, ShopGUIPlus, Shopkeepers, SignEdit*, StaffChat, StaffTime, Stats, SuperLuckyBlock, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, ViaVersion*, Votifier, VotingPlugin, WDLCompanion*, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridg

####  Additional context
```
[12:59:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is biomes' in world.bentobox.acidisland.commands.AiCommand(is)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.13.2.jar:git-Paper-632]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-632]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-632]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-632]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at world.bentobox.biomes.panels.CommonGUI.generateBiomesDescription(CommonGUI.java:248) ~[?:?]
	at world.bentobox.biomes.panels.user.BiomesChooseGUI.createBiomeIcon(BiomesChooseGUI.java:162) ~[?:?]
	at world.bentobox.biomes.panels.user.BiomesChooseGUI.build(BiomesChooseGUI.java:137) ~[?:?]
	at world.bentobox.biomes.commands.user.BiomesCommand.execute(BiomesCommand.java:96) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:246) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-632]
	... 14 more
```

**Comment by BONNe** [comment]
So, I can continue to fix null-pointer error, but it will not solve your issue.
One of your biomes is not set up correctly.

Latest commit will disallow to load it at all.

**Comment by andris155** [comment]
Works perfectly. Thanks!
