### ISSUE TITLE
Biomes doesn't work in 1.14.4

### ISSUE THREAD

**Issue by SirBlobman** [BentoBoxWorld/Biomes#43]
#### Description
Changing the biome causes an error

####  Steps to reproduce the behavior:
1. Create a BSkyBlock island
2. Make sure you have $100
3. Do "/is biomes set ocean"

#### Expected behavior
I expected the island biome to be changed and not have an error

#### Error Stacktrace
```
[15:49:55 WARN]: [BentoBox] Plugin BentoBox v1.5.3 generated an exception while executing task 50
java.lang.IllegalStateException: BiomeChangedEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-154]
        at world.bentobox.biomes.tasks.BiomeUpdateTask.run(BiomeUpdateTask.java:66) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-154]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-154]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-154]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

#### Server Information:
 - Default Storage (YML?)
 - OS: Windows 10 1903
 - Java Version: Java 8

####  Plugins
![image](https://user-images.githubusercontent.com/9003290/62395221-9b9e8300-b53d-11e9-8325-e06bcd19cdd9.png)

#### BentoBox Version
![image](https://user-images.githubusercontent.com/9003290/62395244-abb66280-b53d-11e9-83e9-d2db55e81eea.png)

**Comment by BONNe** [comment]
It is not an important error that is solved in the snapshot version.
