### ISSUE TITLE
/is biomes info <boime>'s errors

### ISSUE THREAD

**Issue by bonjourkemal** [BentoBoxWorld/Biomes#63]
```/is biomes info jungle```

```
[11:39:38] [Server thread/INFO]: Server version PAPER 1.15.2
[11:39:38] [Server thread/INFO]: BentoBox version: 1.12.0
[11:39:38] [Server thread/INFO]: Database: YAML
[11:39:38] [Server thread/INFO]: Loading world list:
[11:39:38] [Server thread/INFO]: skyblock (Skyblock): Overworld, Nether*
[11:39:38] [Server thread/INFO]: Loaded addons:
[11:39:38] [Server thread/INFO]: Biomes 1.7.0
[11:39:38] [Server thread/INFO]: BSkyBlock 1.12.0
[11:39:38] [Server thread/INFO]: Chat 1.0.4
[11:39:38] [Server thread/INFO]: Level 1.9.3
[11:39:38] [Server thread/INFO]: VoidPortals 1.5.0.0
[11:39:38] [Server thread/INFO]: Warps 1.9.0

```

```
[11:36:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is biomes info jungle' in world.bentobox.bskyblock.commands.IslandCommand(island)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.15.2.jar:git-Paper-155]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-155]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_241]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_241]
	at world.bentobox.biomes.commands.ExpandedCompositeCommand.getSingleLineDescription(ExpandedCompositeCommand.java:197) ~[?:?]
	at world.bentobox.biomes.commands.user.BiomesInfoCommand.execute(BiomesInfoCommand.java:46) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-155]
	... 16 more

```

**Comment by bonjourkemal** [comment]
will you not tell me the cause of the problem?

**Comment by BONNe** [comment]
It is written in the commit message. Click on a128d12.
