### ISSUE TITLE
Biomes error

### ISSUE THREAD

**Issue by daoshii** [BentoBoxWorld/Biomes#70]
### Describe the bug
Just trying to change biome from the /island biomes menu. It doesn't do anything and throws this error.

##### Output of `/bbox version` (Mandatory)

```
[05:08:38 INFO]: Running PAPER 1.16.1.
[05:08:38 INFO]: BentoBox version: 1.14.0-SNAPSHOT-b1824
[05:08:38 INFO]: Database: JSON
[05:08:38 INFO]: Loaded Game Worlds:
[05:08:38 INFO]: sblock (sblock): Overworld, Nether*, The End*
[05:08:38 INFO]: Loaded Addons:
[05:08:38 INFO]: Biomes 1.13.0-SNAPSHOT-b173 (ENABLED)
[05:08:38 INFO]: Border 1.0.9-SNAPSHOT-b35 (ENABLED)
[05:08:38 INFO]: BSkyBlock 1.14.0-SNAPSHOT-b661 (ENABLED)
[05:08:38 INFO]: ControlPanel 1.13.0-SNAPSHOT-b22 (ENABLED)
[05:08:38 INFO]: Level 2.3.0-SNAPSHOT-b380 (ENABLED)
[05:08:38 INFO]: Limits 1.14.0-SNAPSHOT-b222 (ENABLED)
[05:08:38 INFO]: MagicCobblestoneGenerator 2.0.0-SNAPSHOT-b114 (ENABLED)
[05:08:38 INFO]: Upgrades 0.1.0-SNAPSHOT-b37 (ENABLED)
[05:08:38 INFO]: Warps 1.9.8-SNAPSHOT-b248 (ENABLED)
```

#### error
```
[05:06:48 ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.14.0-SNAPSHOT-b1824
java.lang.NoSuchMethodError: world.bentobox.level.Level.getLevelsData(Ljava/util/UUID;)Lworld/bentobox/level/objects/LevelsData;
at world.bentobox.biomes.tasks.BiomeUpdateHelper.canChangeBiome(BiomeUpdateHelper.java:132) ~[?:?]
at world.bentobox.biomes.commands.user.BiomesSetCommand.execute(BiomesSetCommand.java:76) ~[?:?]
at world.bentobox.biomes.panels.CommonGUI.callCommand(CommonGUI.java:208) ~[?:?]
at world.bentobox.biomes.panels.user.UpdateModeGUI.lambda$createButton$8(UpdateModeGUI.java:294) ~[?:?]
at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1063.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-46]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-46]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-46]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2421) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-46]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-46]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by tastybento** [comment]
No, this was due to 2.3.0 not being stable. I fixed this issue. Use the latest Level snapshot.
